
const techNames = {
  github: 'GitHub',
  linkedin: 'LinkedIn',
  gmail: 'Gmail',
  react: 'React',
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  nodejs: 'Node.js',
  tailwind: 'Tailwind CSS',
  html: 'HTML',
  css: 'CSS',
  java: 'Java',
  springboot: 'Spring Boot',
  swagger: 'Swagger',
  postgres: 'PostgreSQL',
  mysql: 'MySQL',
  nextjs: 'Next.js',
  googleappsscript: 'Google Apps Script',
  haskell: 'Haskell',
  expressjs: 'Express.js',
  mui: 'Material-UI',
  git: 'Git',
  githubactions: 'GitHub Actions',
  gradle: 'Gradle',
  maven: 'Maven',
  npm: 'npm',
  pnpm: 'pnpm',
  docker: 'Docker',
  jwt: 'JWT',
  cypress: 'Cypress',
  grafana: 'Grafana',
  prometheus: 'Prometheus',
  k6: 'K6',
}